- hosts: local
  connection: local
  become: yes
  become_user: root
  vars:
    user: zilq
    package_manager: dnf

  pre_tasks:
    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.package:
        name: "*"
        state: latest

  roles:
    - dotfiles
    - terminal
    - langs
    - bitwarden
    - starship
    - obsidian
    - discord
    - opencode
