- name: enable ghostty copr
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: pgdev/ghostty
  when: ansible_facts['distribution'] == 'Fedora'

- name: install ghostty via dnf
  ansible.builtin.dnf:
    name: "ghostty"
    state: present
  when: ansible_facts['distribution'] == 'Fedora'

- name: download ghostty .deb package
  ansible.builtin.get_url: 
    url: https://github.com/mkasberg/ghostty-ubuntu/releases/download/1.0.1-0-ppa1/ghostty_1.0.1-0.ppa1_amd64_22.04.deb
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: install ghostty .deb package
  become: yes
  ansible.builtin.shell: dpkg -i ghostty_*.deb
  when: ansible_facts['distribution'] == 'Ubuntu'
